name: Build and publish images
on:
  push:
    paths:
      - '*'
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to ghcr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login ghcr.io -u chestercodes -p $GITHUB_TOKEN

      - name: Set image tag
        run: IMAGE_TAG=$(date +"v%y%m%d%H%M%S") && echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"

      - name: Build images in parallel
        run: docker compose -f docker/build.yaml build --parallel
        working-directory: .

      - name: push images
        run: docker compose -f docker/build.yaml push
        working-directory: .

      - name: Create git tag
        run: |
          git tag $IMAGE_TAG
      - name: Push git tag
        run: git push origin $IMAGE_TAG
