name: PR build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to ghcr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login ghcr.io -u chestercodes -p $GITHUB_TOKEN

      - name: Set image tag
        run: echo "IMAGE_TAG=pr-$GITHUB_SHA" >> "$GITHUB_ENV"

      - name: Build images in parallel
        run: docker compose -f docker/build.yaml build --parallel
        working-directory: .

      - name: push images
        run: docker compose -f docker/build.yaml push
        working-directory: .

